### ISSUE TITLE
Roadmap for v1

### ISSUE THREAD

**Issue by ozbillwang** [aws/aws-cli#5775]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

Amazon Linux 2

**Describe the question**
create a ec2 instance from latest Amazon Linux 2, I found the AWS CLI version is still v1, not v2.  But AWS itself recommend to go with v2, but why its image still doesn't do that?

https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv1.html

Quota from AWS document: 
```
We recommend that you use AWS CLI version 2 instead. 
```

My role is to bake the Base Images for customers, that I am in the middle of aws cli v1 or v2. 

The old exist baked image are all with aws cli v1 currently. 

What would you recommand?

Second, **that's reason I raise ticket here** What's the roadmap for v1? Do you have plan to decommission it or not? Any deprecation plan?

If the answer is not, I would not bothing with the versioning, and go straightforward to use v1

**Comment by kdaily** [comment]
Hi @ozbillwang,

Thanks for your questions.

According to their FAQ (https://aws.amazon.com/amazon-linux-2/faqs/), Amazon Linux 2 has long term support until June 30, 2023. For stability and given the potential for breaking changes (detailed here: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html), the AWS CLI will remain at v1 on the changing the major version on AL2 would have serious repercussions for users.

If you have questions about the release or update cycle for the Amazon Linux 2 AMI, you can reach that team directly on the AWS Amazon Linux Forum:

https://forums.aws.amazon.com/forum.jspa?forumID=228

Secondly, the AWS SDKs have a maintenance policy, which is available here:

https://docs.aws.amazon.com/credref/latest/refdocs/maint-policy.html

You can see there what the current status of all SDKs and tools, including the AWS CLI. The AWS CLI v1 is in the full support phase. Based on this document, you can see that it would be a minimum of 18 months from a maintenance announcement until end of support. There is no plan to make any maintenance announcement for deprecating the AWS CLI v1.

**Comment by ozbillwang** [comment]
Thanks for the detail
